-- V19: 各排放源氣體排放量欄位（tCO₂, tCH₄, tN₂O, tHFCs）
ALTER TABLE activity_records
  ADD COLUMN IF NOT EXISTS co2_t NUMERIC,
  ADD COLUMN IF NOT EXISTS ch4_t NUMERIC,
  ADD COLUMN IF NOT EXISTS n2o_t NUMERIC,
  ADD COLUMN IF NOT EXISTS hfc_t NUMERIC;
